kind: Deployment
apiVersion: apps/v1
metadata:
  name: kuard
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
        - image: docker.pkg.github.com/williamb17/kuard/kuard
          imagePullPolicy: Always
          name: kuard
          resources:
            requests:
              cpu: '100m'
              memory: '768Mi'
            limits:
              cpu: '500m'
              memory: '1024Mi'
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: regcred
